modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Academic Free License v3.0"
[[mods]] #mandatory
modId="occ" #mandatory
version="1.4.2" #mandatory
displayName="Epic Fight: Obsidian Can Cry" #mandatory
authors="Voidy Jam" #optional
description='''${mod_description}'''
[[dependencies.occ]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.2.20,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.occ]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.occ]]
    modId="epicfight"
    mandatory=true
    versionRange="[20.8.1,)"
    ordering="AFTER"
    side="BOTH"